version: '3.9'
services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:13.2
    restart: always
    ports:
      - 5438:5432
    volumes:
      - ./:/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
    name: postgres-data
